//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityframeworkDB.ADO.NET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectionDb2018Entities1 : DbContext
    {
        public ConnectionDb2018Entities1()
            : base("name=ConnectionDb2018Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CacheAnagram> CacheAnagrams { get; set; }
        public virtual DbSet<CacheMap> CacheMaps { get; set; }
        public virtual DbSet<IPLogUser> IPLogUsers { get; set; }
        public virtual DbSet<Word> Words { get; set; }
    }
}
